### ISSUE TITLE
multiple definition errors

### ISSUE THREAD

**Issue by ghost** [bubulindo/MapleRTC#2]
I've added the folder to the library folder in maple, and it shows up in my libraries list.  I'm using the Olimexino STM32 board.  I also replaced the original rcc.h and rcc.c files in my maple lib with the ones in this library and I end up getting quite a few multiple definition errors, even though I see they're only defined once.  Any ideas?

**Comment by rogerclarkmelbourne** [comment]
I'm just porting this to Arduino 1.6.rc1 

Depending on what version you have of Maple, the code organization may be completely different from how it was when this library was written 3 years ago.  

Firstly I'd recommend that perhaps you checkout the repo I manage that adds support for Maple mini to Arduino 1.6.rc1  https://github.com/rogerclarkmelbourne/Arduino_STM32

Or, if you want to stick with your current version of libmaple (perhaps part of the Maple IDE) you are probably going to need to do what I'm currently doing, which is fixing issues line by line, by copying the appropriate new code from rcc.c.new and rcc.h.new into the appropriate files in libmaple

**Comment by ghost** [comment]
I was able to get it working.  I know it's not good trouble shooting, but I performed two steps at once to try and fix it, so I'm not sure which one did it.  The first was that I downloaded the MapleRTC-master zip from sites.google rather than this github repo.  The second, was that I was retaining the original rcc files in the lib maple directory within a separate folder I created.  I ended up moving that to my desktop out of the maple directory.  The two steps in conjunction allowed the RTC-test sketch to compile without errors.

**Comment by rogerclarkmelbourne** [comment]
I got the library to compile by copying some functions from rcc.c.new and rcc.h.new , however at the moment the example sketch doesn't work.

It will look for the version on sites.google.com
